// auth.js
export const LOGOUT = "LOGOUT"
export const SAVE_TOKEN = "SAVE_TOKEN"
export const FETCH_USER = "FETCH_USER"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE"
export const UPDATE_USER = "UPDATE_USER"

// lang.js
export const SET_LOCALE = "SET_LOCALE"

// category.js

export const FETCH_CAT = "FETCH_CAT"
export const FETCH_CAT_SHOW = "FETCH_CAT_SHOW"

export const FETCH_PACKAGE = "FETCH_PACKAGE"
export const FETCH_MYPACKAGE = "FETCH_MYPACKAGE"
export const FETCH_MYPACKAGESHOW = "FETCH_MYPACKAGESHOW"

export const FETCH_PACKAGE_SHOW = "FETCH_PACKAGE_SHOW"

export const FETCH_CART = "FETCH_CART"

export const FETCH_PRODUCT = "FETCH_PRODUCT"
export const FETCH_PRODUCT_ALL = "FETCH_PRODUCT_ALL"
export const FETCH_PRODUCT_SHOW = "FETCH_PRODUCT_SHOW"
